[ch261] Link to datasets filtered by Team name on Homepage when user clicks team name in Sidebar
biglocalnews/reporting-tool pull request #109
Opened 2021-07-27 21:10 UTC by seerocode

Story details: https://app.clubhouse.io/stanford-computational-policy-lab/story/261

### Changes:
1. When a user clicks on a team title from the sidebar (e.g. BBC News), the home table will filter by that team name and hide the search bar
![image](https://user-images.githubusercontent.com/10480484/129293376-fcf3008d-a88e-4e69-b3eb-8cd8f2ab8de6.png)

team name not found:
![image](https://user-images.githubusercontent.com/10480484/129293432-9e17542f-3544-4edb-a204-5bc1e6d4f528.png)

team param value missing:
![image](https://user-images.githubusercontent.com/10480484/129293703-cb09a4f3-b495-4f39-90f7-04c821fd5bb4.png)

2. Added home button to sidebar to make navigation easier for user
3. When no results are found in search, table shows no data:
![image](https://user-images.githubusercontent.com/10480484/129593610-20c10e6f-de2f-4c4d-969f-20409b278cb4.png)

TODO:
- [X] return no data if filter on home table is not found
- [X] if filtering by team name only, table filter should only search the "team" column

2021-08-02 19:46 UTC, jnu requested changes
made a few suggestions which will hopefully clean up searching a bit. overall looks great, nice work!!

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +          message={`Showing datasets for team: ${teamNameFilter.toUpperCase()}`}
can this use the translation file?

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +    if (teamNameFilter) {
a couple thoughts on this:
1) the `handleTableSearchFilteredData` function doesn't strictly filter by team name. we might end up with false positives where a team name is a subset of an unrelated dataset name. a low-key way to fix this is add support for structured queries. this doesn't have to be super fancy, a low-key way to do this might look like:
```ts
// Support structured queries like "team:foo"
const queryParts = searchText.toLowerCase().split(/:(.*)/, 2);
// All the columns we allow searching on
const allColumns = ["dataset", "team", "program"];
// If it's not a structured query, add a placeholder empty string
if (queryParts.length < 2) {
  queryParts.unshift("");
}
// Make sure that the parsed column is a real column. If it's not,
// revert the parsing to treat it as though no column was given.
if (queryParts[0] && !allColumns.includes(queryParts[0])) {
  queryParts[1] = queryParts.join(":");
  queryParts[0] = "";
}
const [column, query] = queryParts;
// Filter all the source rows
const filtered = data.filter(row => {
  // For structured search, only return matches on the given column
  if (column) {
    return row[column].toLowerCase().includes(query);
  }
  // Otherwise search all columns
  return allColumns.some(col => row[col].toLowerCase().includes(query);
});
```

then we could support things like `?filter=team:foo` or `?filter=program:some%20program`

2) do we ever want the value that a user types in the autocomplete to sync back to the URL `?filter=`? might be useful for sharing queries
3) no need to bail early here if the team name filter is missing, especially if you bail early in the `handleTableSearchFilteredData` function on the empty string.

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +    const data = [...allTableData];
looks like `searchText` ought to be `toLowerCase`d here

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +    const data = [...allTableData];
also you can also return early if `searchText` is the empty string since `includes` will always be true

2021-08-02 19:46 UTC, jnu commented on client/src/layout/AppSidebar.tsx
> +                        search: `?filter=${program.team}`,
you should call `encodeURIComponent` on the team name. in particular if the team name contains an `&` this will not behave as expected.

(see also my structured search comment elsewhere. another option would be to have different query params, like `?team=${encodeURIComponent(program.team)}`)

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +          ? `Showing ${filteredData.length} of ${rowData.length} results`
can these come from i18n translations?

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +              <Button icon={<InfoCircleOutlined />}>View Details</Button>
can this use i18n?

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +      render: function btn(datasetId: string) {
just curious, why is this not an arrow function? (if it's due to the name linting, i usually move it out to a separate `const` which i think makes the code more readable anyway)

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +            // TODO: Create component to link tags to datasets with the same tags
is this tracked somewhere?

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +              {tag.toUpperCase()}
curious why we're upper-casing tags? just fyi tags are normalized on the backend to all have capitalized first letters

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +      dataSource={filteredData.length > 0 ? filteredData : rowData}
hm - so if there are no matches for a query we show everything? that seems potentially odd to me

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeSearchAutoComplete.tsx
> +  const searchBarLabel = "Search team and dataset";
can this come from i18n?

2021-08-02 19:46 UTC, jnu commented on client/src/pages/Home/HomeSearchAutoComplete.tsx
> +      <label htmlFor="Search">
for accessibility, the label's `for` attribute needs to have the value of an `id` of an element (maybe there's a `#Search` element here but and im missing it?)

2021-08-03 16:11 UTC, seerocode commented on client/src/pages/Home/Home.tsx
> +    if (teamNameFilter) {
Good points here! What if I do a followup PR for this instead right after this is merged?

2021-08-03 17:32 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +              {tag.toUpperCase()}
They were uppercase before the backend was changed to capitalize all letters. Also looks better UI wise IMO.

2021-08-03 17:34 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +      dataSource={filteredData.length > 0 ? filteredData : rowData}
Yeah this is something I'm fixing (added as a TODO here). The dataset query doesn't load until after the component is rendered.

2021-08-03 17:36 UTC, seerocode commented on client/src/pages/Home/HomeSearchAutoComplete.tsx
> +      <label htmlFor="Search">
Didn't miss it but I did. I'll add the id to the auto complete wrapper.

2021-08-11 19:41 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +            // TODO: Create component to link tags to datasets with the same tags
Yeah this was already being tracked here: https://app.clubhouse.io/stanford-computational-policy-lab/story/163/decide-how-to-present-tags

Deleted comment since the story exists.

2021-08-16 16:18 UTC, nmanduj1 commented on client/src/App.css
> +  clip-path: inset(50%);
fancy css- ive never seen "clip" before!

2021-08-16 16:24 UTC, nmanduj1 approved these changes
looks good to me! 🚢

2021-08-16 17:16 UTC, seerocode commented on client/src/pages/Home/Home.tsx
> +    if (teamNameFilter) {
@jnu I added this comment to the structured search ticket so it can be worked on with this in mind: https://app.clubhouse.io/stanford-computational-policy-lab/story/301/structured-search-in-filter-bar

In the meantime, since the param is used to filter the data in the table, I added the data filter as a side effect instead.

2021-08-16 20:00 UTC, jnu approved these changes
looks good, made a few stylistic comments but nothing major! nice work!

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +    if (data && !search) {
you could clean up the code a bit by using explicit return statements, instead of re-evaluating conditions like `data`. for example:

```ts
if (!data) {
  return;
}

if (!search) {
  setFilteredData(allTableData);
  return;
}

if (teamNameURLParam) {
  const filter = ...;
  setFilteredData(filter);
  return;
}
```

that way the code doesn't have to keep evaluating redundant and/or unnecessary conditions. it also makes the code a little easier to read for humans, since you don't have to keep all the different states in mind while reading to the end of the function. i would guess this helps avoid errors in refactoring later.

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +        team.includes(searchText.toLowerCase()) ||
slightly better to store `searchText.toLowerCase()` in a variable so you don't have to do the operation multiple times

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/Home.tsx
> +      <>{t("missingTeamParam")}</>
is there a reason this text has to be wrapped in a fragment? (usually you can use text directly as a react node, and `<>text</>` is rendered identically to `text`, but maybe something weird is going on with the typings in antd?)

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +        searchWords={[searchText.toString()]}
why do we need to call `toString` here? it looks like the type of `searchText` is already a string?

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +        textToHighlight={text ? text.toString() : ""}
again why is toString necessary? 🤔

2021-08-16 20:00 UTC, jnu commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +      const color = "blue";
it's better not to hardcode colors like this, for two reasons. first is general DRYness, it's almost always better to define constants rather than have strings scattered around the application, so that it's easier to change later on.

second is that especially for colors, our goal is to make the app themeable. the technique to do that usually consists of two parts: 1) a color palette consisting of specific RGB colors, and 2) a theme that assign semantic value using those colors.

for example:

```ts
const palette = {
  blue: "#2323e8",
  orange: "#e88623",
};

const theme = {
  primary: palette.blue,
  accent: palette.orange,
};
```
then in your UI you reference the theme values, and *not* the colors from the palette directly. for example:

```ts
<Tag color={theme.primary}>{tag}</Tag>
```
this lets us define a custom color palette and/or theme without changing any of the UI code. so we could for example swap out the theme at buildtime, or even at runtime, to make the app fit in with any organization's in-house style.

you don't have to develop the theming capabilities fully now (that would include things like fonts, logos, etc), but we should at least try to avoid having colors defined in random places in the UI, so that it's easier to update later.

2021-08-16 20:01 UTC, seerocode commented on client/src/pages/Home/Home.tsx
> +    if (data && !search) {
thank you! this helps a lot. i'll make the changes.

2021-08-16 20:16 UTC, seerocode commented on client/src/pages/Home/Home.tsx
> +      <>{t("missingTeamParam")}</>
Thanks for catching this! I had refactored this earlier and yes this does not need to be wrapped in a fragment. The following false condition does though. I felt splitting up as prefix and suffix made the translation more readable.

2021-08-16 20:17 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +        textToHighlight={text ? text.toString() : ""}
This is straggler stuff when I was refactoring an ant design highlight example. I'll clean up.

2021-08-16 20:21 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +        searchWords={[searchText.toString()]}
Fixed.

2021-08-16 20:33 UTC, seerocode commented on client/src/pages/Home/HomeDatasetsListTable.tsx
> +      const color = "blue";
Fair point! I remember this was taken directly from ant design code and it seems they have since updated how they render color tags. I moved the color to a config file for now along with the orange color for text highlight.

2021-08-16 20:46 UTC, merged