Ch133/data entry mutation
biglocalnews/reporting-tool pull request #32
Opened 2021-04-12 16:48 UTC by nmanduj1

Add create_dataset resolver logic

2021-04-13 01:28 UTC, jnu requested changes
this is awesome, nice work!!! im mainly focused on the transaction / session logic here because that can be tricky stuff that's hard to get right. if you have other things you want me to look at in particular let me know!

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +session = SessionLocal()
did you see an example that did something like this? typically you don't wanna create a session in a global scope like this, because then you only have one single session spanning the lifetime of the application. instead, sessions in a webapp should only last the lifetime of a single request.

In FastAPI they use this "dependency" pattern here: https://fastapi.tiangolo.com/tutorial/sql-databases/#create-a-dependency

This creates a single session for the lifetime of the request. It's a little weird to do this with Ariadne, but it looks like possibly the `info.context` object is a good place to store the session -- this is a kind of tricky bit, lmk if you wanna pair on it!

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +    #TODO Flush vs Commits??
should be safe to just use `commit` always, since it calls `flush` for you, and not worry about the technical distinction.

(in a database transaction, you can run a lot of commands on a database to insert/delete/update records and they won't be saved by the database until you call "commit". SQLAlchemy has a similar system for modifying your data within python, which you can then _flush_ to send those operations in a transaction to the database, which will then save them when you call _commit_.)

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +        "inputter_id": '3dd10e5f-be57-435c-b721-28f3ced5dc89',
why is this one hardcoded and not coming from `input`?

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +    session.commit()
we should probably only call `commit` one single time, once we've added everything to the session. the reason being, if anything goes wrong partway through this update, we don't want to have a partially-completed update in the database --- we'd rather have everything _rolled back_ as a single unit.

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +    persisted_dataset["tags"] = map(lambda tag: tag.__dict__, persisted_dataset["tags"])
it's almost always better/faster in python to use that _list comprehension_ syntax instead of the `map` function. so here:
```py
[tag.__dict__ for tag in persisted_dataset['tags']]
```

2021-04-13 01:28 UTC, jnu commented on api/mutations.py
> +    session.add(dataset)
as i mentioned in the other comment, the `session` really needs to be scoped to within the lifetime of a single request, and not shared between requests. (otherwise we'll end up seeing a bunch of incorrect updates and potential security flaws when we have multiple users using the app at once!!)

the simplest thing to do is just create a new `session` within each mutation and `close` it at the end.

a slightly fancier thing is to create the `session` with a dependency as in the FastAPI docs, and then put that in the `info.context` that gets shared throughout all the graphql resolvers.

2021-04-13 18:04 UTC, seerocode commented on api/schema.graphql
> +  createDataset(input: CreateDatasetInput): Dataset!
Should there be a "createRecord" mutation here as well or is that a different story/PR?

2021-04-13 18:06 UTC, jnu commented on api/schema.graphql
> +  createDataset(input: CreateDatasetInput): Dataset!
there definitely should be -- i don't mind if they're all in the same pr or in different ones

2021-04-14 14:04 UTC, nmanduj1 commented on api/mutations.py
> +session = SessionLocal()
Interesting! Is there a way to use a session without having to pass it in as an argument at all?

2021-04-14 14:15 UTC, nmanduj1 commented on api/mutations.py
> +        "inputter_id": '3dd10e5f-be57-435c-b721-28f3ced5dc89',
o! bc i was testing and have one sole user in my db- i will pull that out!

2021-04-14 14:27 UTC, nmanduj1 commented on api/schema.graphql
> +  createDataset(input: CreateDatasetInput): Dataset!
I figured I'd add them as I worked on them- "deleteUser" and "upsertUser" are here from testing the original scaffolding.

2021-04-14 14:29 UTC, nmanduj1 commented on api/mutations.py
> +    persisted_dataset["tags"] = map(lambda tag: tag.__dict__, persisted_dataset["tags"])
fancy fancy! I will update

2021-04-14 21:11 UTC, nmanduj1 commented on api/mutations.py
> +    session.add(dataset)
okedokes, i added a simple session within each mutation for now-

2021-04-14 21:34 UTC, jnu approved these changes
woohoo!! this looks great!

@seerocode do you wanna review and make sure the schema changes aren't going to clash with anything you're doing in your branch?

2021-04-14 21:44 UTC, seerocode approved these changes
🚀 looks good to me, no conflict on my end

2021-04-14 22:17 UTC, merged