[ch282] Add person type
biglocalnews/reporting-tool pull request #85
Opened 2021-07-07 20:18 UTC by seerocode

Story details: 
- https://app.clubhouse.io/stanford-computational-policy-lab/story/282
- https://app.clubhouse.io/stanford-computational-policy-lab/story/283/update-ui-to-support-basic-entry-by-person-type

### Changes:
- Added person type to category sections in entry form if person type exists
![image](https://user-images.githubusercontent.com/10480484/126207110-a08dd3ab-5d5f-46c2-b48d-61f71d2b3695.png)
- Added `personType` to `Entry` and `Dataset` as array (no new table for now so it is not in normal form)

2021-07-19 18:49 UTC, seerocode commented
The styling for the titles makes me 😞 but I wanted to get this out there for now and we can hash out what the styles should be!

2021-07-19 18:51 UTC, seerocode commented on api/database.py
> +    person_types = Column(ARRAY(String(255)))
Looks like using an array is a problem so will need to refactor this to get the tests to pass. Doing a new table is a pain but might be better in the long run.

2021-07-19 18:56 UTC, seerocode commented on api/schema.graphql
> +  personType: String
I added personType to the entry so we can update entries based on the type of person they are entering a count for.

2021-07-19 18:56 UTC, seerocode commented on api/schema.graphql
> +  personType: String
Adding it to a record would mean users would have to click in and click out to add entries for the same date but different person type.

2021-07-19 18:56 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryAggregateDataEntryForm.tsx
> +    while (startIndex < addDataEntriesCollectionLen) {
There's probably a better way to set this index (where the number of items for "adding" entries is going to be the number of targets multiplied by the number of person types).

2021-07-19 18:56 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +  if (Array.isArray(personTypes) && !personTypes?.length) {
There's some duplication here between the return functions in this component that could be cleaned up. Noting it here in case I'm overlooking something obvious that could quickly clean this up.

2021-07-19 19:44 UTC, seerocode commented on api/database.py
> +    person_types = Column(ARRAY(String(255)))
Created a table instead.

2021-07-19 20:27 UTC, jnu requested changes

2021-07-19 20:27 UTC, jnu commented on api/database.py
> +entry_person_types = Table('entry_person_type', Base.metadata,
i'm curious why this is many:many? shouldn't it just be one person_type associated with one entry? no need for a mapping table for that, just have a foreign key column on the Entry referencing the PersonType table.

2021-07-19 20:27 UTC, jnu commented on api/database.py
> +    person_types = relationship('PersonType', back_populates='entries')
ah, i see the mapping table is not being referenced here. i would delete the mapping table above and call this `person_type` singular, since a single entry can only have one associated person type.

the relationship is `many:1` -- so many entries will be associated with one single PersonType row. I would expect data access to typically be in that direction (i.e., joining the PersonType to the Entry table), and the reverse relationship of querying all the entries associated with a singular PersonType may never happen in practice, since for reporting we would probably always want several other filters (e.g. by program or region or tag or whatever), bu it's fine to keep `PersonType.entries` if you want.

2021-07-19 21:10 UTC, jnu requested changes
looks pretty close, great work! i made a few comments to hopefully help clean it up a bit, let me know if there's any way i can help!

2021-07-19 21:10 UTC, jnu commented on api/database.py
> +from sqlalchemy.sql.sqltypes import ARRAY, TIMESTAMP
can you clean up the ARRAY type here?

2021-07-19 21:10 UTC, jnu commented on api/schema.graphql
> +  personTypes: [PersonType!]
this should be `[PersonType!]!` i think since it'll never be null, right?

2021-07-19 21:10 UTC, jnu commented on api/schema.graphql
> +  personType: PersonType
should this be `PersonType!` since it'll never be null?

2021-07-19 21:10 UTC, jnu commented on client/public/locales/en-gb/translation.json
> +  "cancelAndReturnToDashBoard": "Cancel and Return To Dashboard",
it looks like these all duplicate the `en/translation.json`? we only have to specify translations here if they differ from the general english translation.

2021-07-19 21:10 UTC, jnu commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +export const PageTitleBar: React.FC<DefaultProps> = (
it looks like this component just provides styling. what's the advantage of writing a new component for this vs. simply overrriding the `.ant-page-header` class style in css?

2021-07-19 21:10 UTC, jnu commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +      title={<Text style={{ fontSize: "x-large" }}>{titleBarProps.title}</Text>}
I'm not sure what the PageHeader component renders internally, but for accessibility it's better to use semantic header rank tags like `<h1 />` instead of simple Text elements (i assume antd just uses <span> for these).

https://www.w3.org/WAI/tutorials/page-structure/headings/

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryAggregateDataEntryForm.tsx
> +    while (startIndex < addDataEntriesCollectionLen) {
hm i'm wondering why the startIndex is needed at all? isn't that just the same as the array index of the object? either way i don't see what wrapping in the `while` loop adds, since every single time this code runs the check will be false on the first pass and true on the second pass.

simpler:

```ts
for (const personType of metadata?.dataset.personTypes) {
  for (const target of metadata?.dataset.program.targets) {
    form.push({
      /* type + target + count stuff. i wouldn't include the index. */
    });
  }
}
```
then if you need the index later you can get it when you iterate:
```ts
form.map((formItem, index) => /* stuff */);
```
 

but maybe i'm missing something? if you do the need the index, you could also just set `let index = 0` before the loop and set `index: index++` as you go, no need for the outer while loop.

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryAggregateDataEntryForm.tsx
> +    metadata?.dataset?.program?.targets.map((target, index) => {
i'm still a little confused why personType would be null - but if so, you could combine this with the upper loop by doing:

```ts
const personTypes  = metadata?.dataset.personTypes || [undefined];
for (const personType of personTypes) {
  for (const target of metadata?.dataset.program.targets) {
    form.push({
      // target stuff
      count: 0,
      personType, // this will be `undefined` when no personTypes are specified, and therefore semantically the same as what you have here.
    });
  }
}
```
it's nice eliminate conditional code paths like this when possible so there's less code to keep in sync.

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +        <input
is it possible to use the antd `Input` component here to keep styling consistent?

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          className="data-entry-form_required-field"
fwiw antd Forms provide validation to address the required field use case

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +  const inputs = (entries: any) => {
do we have a more specific type for this?

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +        key={item.index}
is this the only place we use the `item.index` i commented on above? in this case it's actually better to not use the numeric index anyway.

react requires a unique key of some sort, the more semantically meaningful you can make those keys the better react will perform. using numeric index keys is a last resort because they index is arbitrary -- the list could be reordered without affecting the elements, which thrashes performance and can also lead to incorrect rendering. (more info here: https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318).

i think for these you want the key to be some combination for `personType + target`, right? the personType name and the target categoryValueLabel would ideally be the key.

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +        id={item.categoryValueLabel}
html IDs should be unique across the entire page, which is not true here when there are multiple personTypes. this ID should probably just be the same as the key you use

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          key={index}
fwiw you only need keys when you render a list of components. (i.e., only the outermost component in each list item needs a key.)

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          inputMode="numeric"
antd has a NumberInput component, does that work here?

the numeric input component used to vary pretty significantly between browsers. maybe that's fixed, my gut is that it'd be better to use a component from the framework for visual consistency + cross browser compatibility.

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          onChange={(e) => onValueChange(e, item.index)}
`item.index` will be the same as `index` right?

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +  if (Array.isArray(personTypes) && !personTypes?.length) {
hm, when is this condition true? "personTypes is an array and has no elements in it" -- i thought either personTypes was `null` if the dataset didn't use personTypes, or it'd have some elements in it?

2021-07-19 21:10 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +  if (Array.isArray(personTypes) && !personTypes?.length) {
in general i would think it's possible to reuse the code by checking if personTypes is missing, and if so, add a trivial generic personTypes list of length 1 (as i mentioned above with using `[undefined]` as the base case to reuse code in the loops).

2021-07-19 21:14 UTC, seerocode commented on api/database.py
> +entry_person_types = Table('entry_person_type', Base.metadata,
This was already deleted in recent commits.

2021-07-19 21:15 UTC, seerocode commented on api/schema.graphql
> +  personTypes: [PersonType!]
It can be null if no person Type is assigned to a dataset.

2021-07-19 21:15 UTC, seerocode commented on api/schema.graphql
> +  personType: PersonType
It can be null if no person type exists for a dataset so it will not exist for the entry.

2021-07-19 21:17 UTC, seerocode commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +export const PageTitleBar: React.FC<DefaultProps> = (
Because this component is used in other places too (like Admin side) and styling is inconsistent. You'd have to copy the style code over each time you use the page header. This also requires the title and subtitle instead of making it optional again for consistency.

2021-07-19 21:17 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          key={index}
Yeah this was carryover while I was moving things around.

2021-07-19 21:18 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          inputMode="numeric"
I'm hesitant to use it because I've seen accessibility issues with it. Namely that scrolling up or down on a mouse inadvertently moves numbers up and down possibly without the user realizing. If this is disable by default in the component then I can try it.

2021-07-19 21:20 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          onChange={(e) => onValueChange(e, item.index)}
I thought so but there's a glitch with indices loading out of order so this makes it consistent.

2021-07-19 21:20 UTC, jnu commented on api/schema.graphql
> +  personTypes: [PersonType!]
the way many:many relationships work in sqlalchemy, `Dataset.person_types` will just be an empty list if there's nothing assigned (not `None`). since this is reliably the case, if you add the `!` type restriction on the list you won't have to make `null` checks everywhere in typescript when you want to reference this list. (it'll also keep us from trying to give a `null` value any semantics, since there will never be a null value for this field.)

2021-07-19 21:23 UTC, jnu commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +export const PageTitleBar: React.FC<DefaultProps> = (
> you'd have to copy the style code over each time you use the page header.

what do you mean by that? css styles are global, you could define a style for `.ant-page-header` in any css file and it'll apply to everywhere that class is used in the application.

2021-07-19 21:26 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          onChange={(e) => onValueChange(e, item.index)}
this sound potentially like a bug that can happen when you use the list index as the `key` prop -- maybe try changing that and see if it's still broken?

2021-07-19 21:52 UTC, jnu commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          inputMode="numeric"
i don't have a mouse wheel to test with (i'm not sure if trackpads behave differently), but it sounds like that's the behavior of `<input type="number" />` in some browsers too? https://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number

either way it should be easy to disable with `onScroll={e => e.preventDefault()}` or something to that effect.

also again i'd just be cautious that the native `input type="number"` is not consistently implemented across browsers either, so there are potentially accessibility and usability concerns with that route too. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#using_number_inputs

2021-07-20 00:25 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryAggregateDataEntryForm.tsx
> +    while (startIndex < addDataEntriesCollectionLen) {
Makes more sense. Thanks! I've been looking at this for too long.

2021-07-20 00:25 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryAggregateDataEntryForm.tsx
> +    while (startIndex < addDataEntriesCollectionLen) {
I also wanted to avoid the nested loop but it's more readable.

2021-07-20 01:38 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +  if (Array.isArray(personTypes) && !personTypes?.length) {
the schema returns an empty array if no person types have been defined for the dataset:

![image](https://user-images.githubusercontent.com/10480484/126249006-342155a3-e9ad-42bb-ba0f-d182e689132c.png)

2021-07-20 01:49 UTC, seerocode commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +export const PageTitleBar: React.FC<DefaultProps> = (
I see what you mean. I can make that global change then although I preferred to isolate it to a component so there's no confusion if someone wants to use the page header in another component that doesn't require that level of consistent styling. Although because CSS cascades, I suppose that won't be an issue.

Here's an example of how it looks now btw:

User -
![image](https://user-images.githubusercontent.com/10480484/126249960-9d0f44fd-e32f-4be2-a4cb-e46ae18ea6ca.png)

Admin - 
![image](https://user-images.githubusercontent.com/10480484/126249980-e96bae6f-cb51-458d-a011-01b499746169.png)

2021-07-20 03:46 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          className="data-entry-form_required-field"
I added the rule and left this asterisk label for visual explicitness that this field is required. I prefer the labels on the right how we decided in our design so it could read as "X people" instead of "people X".

2021-07-20 03:47 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +        id={item.categoryValueLabel}
Thank you. I noticed this too while debugging the tests.

2021-07-20 03:47 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +        key={item.index}
Yeah, exactly. I picked up the same while debugging tests.

2021-07-20 16:24 UTC, seerocode commented
Not sure what's up with the Python tests! @nmanduj1 @jnu any ideas?

2021-07-22 01:46 UTC, jnu approved these changes
thanks ro! 

it does look like all my lingering comments are pretty minor so we should go ahead and merge! awesome work!

2021-07-22 01:46 UTC, jnu commented on api/schema.graphql
> +  personTypeName: String!
this could just be `name`, `personType` is redundant with the name of the type

2021-07-22 04:03 UTC, merged

2021-07-22 13:26 UTC, seerocode commented on client/src/components/PageTitleBar/PageTitleBar.tsx
> +export const PageTitleBar: React.FC<DefaultProps> = (
This was updated btw!

2021-07-22 13:29 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          onChange={(e) => onValueChange(e, item.index)}
It still didn't work without the explicit index so I tabled it to get it through for now. Added a story for it: https://app.clubhouse.io/stanford-computational-policy-lab/story/337/indices-for-entries-in-data-entry-form-load-out-of-order

2021-07-22 13:29 UTC, seerocode commented on client/src/pages/DataEntry/DataEntryCategorySections.tsx
> +          inputMode="numeric"
This was changed to ant design input as well.